### PR TITLE
Update notification from half open to Open state

### PR DESCRIPTION
**Pull request by rupamroy**
### What

When we move from half-open to open state - the event notification is missing. I would like to include that.

### CODE REVIEW

**Comment by rupamroy** [comment]
Can the owner of this repo kindly look into this PR.

**Comment by rupamroy** [comment]
Can the owner kindly merge this  PR.

**Comment by niftymonkey** [comment]
Yes please!  Someone please merge this.

**Review by unindented — APPROVED** [review]

**Comment by unindented** [comment]
I just saw this, 3 years later. 😓

**Pull request merged**
